version: '3.8'

services:
  api:
    build: ./
    env_file:
      - ./.env
    volumes:
      - ./src:/opt/app/src
  redis:
    image: redis:7.2.1-alpine
    volumes:
      - redis_data:/data:rw
  db:
    image: postgres:14.9-alpine3.18
    env_file: 
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  nginx: 
    image: nginx:1.19.3 
    ports: 
      - 80:80
    expose:
      - 80
    restart: always
    depends_on:
      - api
    volumes: 
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/site.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  redis_data: